export const DEPARTMENTS = [
  'CS',
  'Math',
  'English',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Philosophy',
  'Economics',
  'Psychology',
  'Sociology',
  'Engineering',
  'Medicine',
  'Law',
  'Architecture',
  'Arts',
  'Music',
  'Education',
  'Business',
  'Political Science',
  'Nursing',
  'Pharmacy',
  'Dentistry',
  'Veterinary Medicine',
  'Environmental Science',
  'Geography',
  'Anthropology',
  'Linguistics',
  'Communications',
  'Journalism',
  'Theater',
  'Film Studies',
  'Statistics',
  'Astronomy',
  'Geology',
  'Marine Biology',
  'Neuroscience',
  'Public Health',
  'Social Work',
  'Criminal Justice',
];

export const DEPARTMENT_OPTIONS = DEPARTMENTS.map((dept) => ({
  value: dept,
  label: dept,
}));
